WebUI/Controllers/CardTariffsController.cs
using Application.DTO;
using Application.DTO.BankProductDto;
using Application.DTO.FiltersDto;
using Application.ServiceContracts.BankServiceContracts;
using Application.ServiceContracts.ICardTarrifsService;
using Microsoft.AspNetCore.Mvc;
using WebUI.Filters;

namespace WebUI.Controllers
{
    public class CardTariffsController : Controller
    {
        private readonly ICardTarrifsReadService _cardTarrifsReadService;
        private readonly ICardTarrifsAddService _cardTarrifsAddService;
        private readonly ICardTarrifsUpdateService _cardTarrifsUpdateService;
        private readonly ICardTarrifsDeleteService _cardTarrifsDeleteService;
        private readonly IBankReadService _bankReadService;

        public CardTariffsController(ICardTarrifsReadService cardTarrifsReadService, ICardTarrifsAddService cardTarrifsAddService,
            ICardTarrifsUpdateService cardTarrifsUpdateService, ICardTarrifsDeleteService cardTarrifsDeleteService, IBankReadService bankReadService)
        {
            _cardTarrifsReadService = cardTarrifsReadService;
            _cardTarrifsAddService = cardTarrifsAddService;
            _cardTarrifsUpdateService = cardTarrifsUpdateService;
            _cardTarrifsDeleteService = cardTarrifsDeleteService;
            _bankReadService = bankReadService;
        }

        //Read
        [Route("/cards")]
        public async Task<IActionResult> CardTariffsList()
        {
            Response.Cookies.Append("returnUrl", "cardTariffs");
            Response.Cookies.Append("returnActionUrl", "cardTariffsList");
            ViewBag.Count = await _cardTarrifsReadService.GetCardsCount(new CardTariffsFilters());
            return View(await _cardTarrifsReadService.GetCardsAsync(new CardTariffsFilters()));
        }

        [HttpPost("/get-card-tariffs")]
        public async Task<IActionResult> LoadCards(CardTariffsFilters filters)
        {
            ViewBag.Count = await _cardTarrifsReadService.GetCardsCount(filters);
            return PartialView("_LoadCardTariffs", await _cardTarrifsReadService.GetCardsAsync(filters));
        }

        [Route("card-tariffs-info/{cardId:guid}")]
        public async Task<IActionResult> CardTariffsInfo(Guid cardId)
        {
            Response.Cookies.Append("returnActionUrl", "cardTariffsInfo");
            ViewBag.ReturnUrl = Request.Cookies["returnUrl"];
            return View(await _cardTarrifsReadService.GetCardById(cardId));
        }

        //Add Actions
        [HttpGet("/add-card-tariffs/bank-id/{bankId:guid}")]
        public async Task<IActionResult> AddCard([FromRoute] Guid bankId)
        {
            ViewBag.ReturnUrl = Request.Cookies["returnUrl"];
            ViewBag.BankId = bankId;
            ViewBag.BankName = await _bankReadService.GetBankNameById(bankId);
            return View(new CardTariffsDto());
        }

        [TypeFilter(typeof(ModelBindingFilter))]
        [HttpPost("/add-card-tariffs/bank-id/{bankId:guid}")]
        public async Task<IActionResult> AddCard([FromRoute] Guid bankId, [FromForm] CardTariffsDto cardDto)
        {
            ViewBag.ReturnUrl = Request.Cookies["returnUrl"];
            ViewBag.BankId = bankId;
            ViewBag.BankName = await _bankReadService.GetBankNameById(bankId);
            if (ModelState.IsValid)
            {
                OperationResult result = await _cardTarrifsAddService.AddCardAsync(cardDto);
                ViewBag.Message = "Success!";
                if (!result.Success) {
                    ViewBag.Message = "Error!";
                    List<string> errors = new List<string>();
                    errors.Add(result.ErrorMessage);
                    ViewBag.Errors = errors;
                }
            }
            return View(cardDto);
        }

        //Update 
        [HttpGet("/update-card-tariffs/card-id/{cardId:guid}")]
        public async Task<IActionResult> UpdateCard ([FromRoute] Guid cardId)
        {
            ViewBag.ReturnActionUrl = Request.Cookies["returnActionUrl"];
            CardTariffsDto? card = await _cardTarrifsReadService.GetCardById(cardId);
            ViewBag.BankName = await _bankReadService.GetBankNameById(card.BankId);
            return View(card);
        }

        [TypeFilter(typeof(ModelBindingFilter))]
        [HttpPost("/update-card-tariffs/card-id/{cardId:guid}")]
        public async Task<IActionResult> UpdateCard([FromRoute] Guid cardId, [FromForm] CardTariffsDto cardDto)
        {
            ViewBag.ReturnActionUrl = Request.Cookies["returnActionUrl"];
            ViewBag.BankName = await _bankReadService.GetBankNameById(cardDto.BankId);
            if (ModelState.IsValid)
            {
                OperationResult result = await _cardTarrifsUpdateService.UpdateCardAsync(cardId, cardDto);
                ViewBag.Message = "Success!";
                if (!result.Success)
                {
                    ViewBag.Message = "Error!";
                    List<string> errors = new List<string>();
                    errors.Add(result.ErrorMessage);
                    ViewBag.Errors = errors;
                }
            }
            return View(cardDto);
        }

        //Delete
        [HttpDelete("DeleteCard/{cardId}")]
        public async Task<IActionResult> DeleteCard(Guid cardId)
        {
            await _cardTarrifsDeleteService.DeleteCardAsync(cardId);
            return Ok();
        }

        [HttpPost("/delete-card-with-redirect/{cardId}")]
        public async Task<IActionResult> DeleteCardWithRedirect(Guid cardId)
        {
            Guid banksId= (await _cardTarrifsReadService.GetCardById(cardId)).BankId; 
            await _cardTarrifsDeleteService.DeleteCardAsync(cardId);
            if(Request.Cookies["returnUrl"]== "cardTariffs")
            {
                return RedirectToAction("CardTariffsList");
            }
            else
            {
                return RedirectToAction("Bank", "BankInfo", new {bankId= banksId });
            }
        }
    }
}

WebUI/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace WebUI.Controllers
{
    public class LanguageController : Controller
    {
        [HttpPost("/change-language")]
        public IActionResult SetLanguage([FromForm] string culture, [FromForm] string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires =  DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

WebUI/Views/Shared/ChoseBank.cshtml
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}


@model List<BankDto>

<div class="main-content-block">
	<h4 id="chose-bank">@Localizer["choseToAddCard"]</h4>
	<span id="span-info" data-entity="@ViewBag.Entity" style="display:none"></span>
	<span class="elements-count" data-elements-list-count="@ViewBag.Count" style="display: none"></span>

	<div id="elements-block">
		@foreach (BankDto bank in Model)
		{
			<div class="element-block">
				<a href="/add-@ViewBag.Entity/bank-id/@bank.Id" class="text-reset text-decoration-none info-card">
					<img src="/@bank.BankLogoPath" alt="Bank logo" class="logo" />
					<table class="element-table">
						<tr>
							<th>
								@bank.BankName
							</th>
						</tr>
						<tr>
							<th class="d-flex flex-row gap-2">
								<img src="~/images/main-page/star.svg" alt="rating" class="rating-icon" />
								@bank.Rating
							</th>
						</tr>
						<tr>
							<th>
								@Localizer["weHave"] @bank.ActiveClientsCount @Localizer["activeClients"]
							</th>
						</tr>
					</table>
				</a>
			</div>
		}
	</div>
	<div class="d-flex flex-row align-items-center action-panel gap-4">
		<button class="load-more" id="load-banks">@Localizer["loadButton"]</button>
	</div>
</div>

@section backButton {
	@switch (ViewBag.ReturnActionUrl)
	{
		case "cardTariffsList":
			<a asp-controller="CardTariffs" asp-action="CardTariffsList" class="text-reset text-decoration-none back-link d-flex align-items-center">
				<img src="~/images/main-page/arrow-to-left-icon.svg" alt="Back" />
			</a>
			break;
		default:
			<a asp-controller="Home" asp-action="Index" class="text-reset text-decoration-none back-link d-flex align-items-center">
				<img src="~/images/main-page/arrow-to-left-icon.svg" alt="Back" />
			</a>
			break;
	}

}
@section ColumsHandler {
	<div id="colums" class="d-flex flex-row gap-1">
		<img src="~/images/main-page/one-column.svg" class="chosen" id="one-column" alt="One column" />
		<img src="~/images/main-page/two-columns.svg" id="two-columns" alt="Two columns" />
	</div>
}
@section Search {
	<form asp-controller="Bank" asp-action="LoadBanksForChose" asp-route-entity="@ViewBag.Entity" id="search" class="d-flex flex-row align-items-center" method="post">
		<div  id="find-element" class="d-flex flex-row align-items-center">
			<input type="text" name="SearchValue" id="search-input" placeholder="@Localizer["enterBankName"]" />
			<button type="button" class="filter-submit-button" id="search-button">@Localizer["searchButton"]</button>
		</div>
		<input type="hidden" name="FirstElement"/>
		<input type="hidden" name="ElementsToLoad"/>
		<!--Sorting-->
		<div id="filters" class="d-flex flex-row align-items-center">
			<img src="~/images/main-page/sort-icon.svg" alt="Sort" id="sort-icon" />
			<div id="sort-list">
				<label>
					<input type="radio" name="SortValue" value="oldest" checked>
					@Localizer["oldest"]
				</label>

				<label class="header-label mt-1">
					<input type="radio" name="SortValue" value="newest">
					@Localizer["newest"]
				</label>

				<label class="header-label mt-1">
					<input type="radio" name="SortValue" value="rating-descending">
					@Localizer["byRating"]
				</label>

				<label class="header-label mt-1">
					<input type="radio" name="SortValue" value="popularity-descending">
					@Localizer["byPopularity"]
				</label>

			</div>
			<img src="~/images/main-page/filter-icon.svg" alt="Filter" id="filter-icon" />

			<!--Filters-->
			<div id="filter-list">
				<label class="header-label">
					<input type="checkbox" name="licenseFilter" class="filter bool-filters" value="false" />
					@Localizer["license"]
				</label>

				<label class="header-label mt-1">
					<input type="checkbox" name="siteFilter" class="filter bool-filters" value="false" />
					@Localizer["sites"]
				</label>

				<label class="header-label mt-1">
					<input type="checkbox" name="filter" value="rating" class="filter value-filter" />
					@Localizer["minRating"]
					<input type="number" name="ratingFilter" class="rating" min="1" max="5" step="0.1" disabled />
				</label>

				<label class="header-label mt-1">
					<input type="checkbox" name="filter" value="clients-count" class="filter value-filter" />
					@Localizer["minClients"]
					<input type="number" name="clientsCountFilter" class="clients-count" min="0" disabled />
				</label>

				<label class="header-label mt-1">
					<input type="checkbox" name="filter" value="capitalization" class="filter value-filter" />
					@Localizer["minCapitalization"]
					<input type="number" name="capitalizationFilter" class="capitalization" min="0" disabled />
				</label>

				<button type="button" class="filter-submit-button" id="submit-filters">@Localizer["useFilters"]</button>
			</div>

		</div>
	</form>
}

@section additionalScripts {
	<script type="module" src="~/js/GenetalListEvents.js" defer></script>
	<script type="module" src="~/js/entities/bank/ChoseBank.js" defer></script>
	@if (ViewBag.Entity == "card-tariffs")
	{
		<script type="module" src="~/js/entities/card-tariffs/cardTariffsMenu.js" defer></script>
	}
}

WebUI/Views/Shared/_GetBanksToChose.cshtml
@{
	Layout = "";
}

@model List<BankDto>
<span class="elements-count" data-elements-list-count="@ViewBag.Count" style="display: none"></span>
@foreach (BankDto bank in Model)
{
	<div class="element-block partial-view-element-block">
		<a href="/add-@ViewBag.Entity/bank-id/@bank.Id" class="text-reset text-decoration-none info-card">
			<img src="/@bank.BankLogoPath" alt="Bank logo" class="logo" />
			<table class="element-table">
				<tr>
					<th class="bank-name-text">
						@bank.BankName
					</th>
				</tr>
				<tr>
					<th class="d-flex flex-row gap-2">
						<img src="~/images/main-page/star.svg" alt="rating" class="rating-icon" />
						@bank.Rating
					</th>
				</tr>
				<tr>
					<th>
						@Localizer["weHave"]  @bank.ActiveClientsCount @Localizer["activeClients"]
					</th>
				</tr>
			</table>
		</a>
	</div>
}

WebUI/Views/Shared/_Layout.cshtml
@inject IViewLocalizer Localizer
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="@Url.Content("~/StyleSheet.css")"/>
    <link href="~/images/favicon/favicon-admin.svg" rel="icon" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
</head>
<body>
    <header class="d-flex flex-row gap-4 align-items-center">
        <div id="header-logo" class="d-flex flex-row ps-4">
            <div id="back-icon">
                @RenderSection("backButton", required: false)
            </div>
            <h2 class="header-info">@Localizer["header"] </h2>
        </div>
        <div id="language">
            <span id="language-name">EN&#9662;</span>
            <form asp-controller="Language" asp-action="SetLanguage" id="chose-language">
                <label>
                    <input type="radio" name="language" value="en-GB" /> EN
                </label>
                <label>
                    <input type="radio" name="language" value="uk-UA" /> UA
                </label>
                <input type="hidden" name="culture"/>
                <input type="hidden" name="returnUrl" value="@Context.Request.Path" />
            </form>
        </div>
        <div id="auth">Auth</div>
    </header>

    <section id="header-functionality">
        <aside>
            <div id="aside-icons">
                <img src="/images/menu/menu.svg" alt="open-menu" id="open-menu" class="">
                <img src="/images/menu/cross.svg" alt="close-menu" id="close-menu" class="clicked">
            </div>

            <ul class="ul-none d-flex flex-column gap-2 align-items-center" id="menu">
                <li id="banks-menu-buttton"><a asp-controller="Bank" asp-action="BanksList" class="text-reset text-decoration-none">@Localizer["banks"]</a></li>
                <li id="card-tariffs-menu-buttton"><a asp-controller="CardTariffs" asp-action="CardTariffsList" class="text-reset text-decoration-none">@Localizer["cards"]</a></li>
                <li><a href="#" class="text-reset text-decoration-none">@Localizer["clients"]</a></li>
                <li><a href="#" class="text-reset text-decoration-none">@Localizer["employees"]</a></li>
                <li><a href="#" class="text-reset text-decoration-none">@Localizer["news"]</a></li>
                <li><a href="#" class="text-reset text-decoration-none">@Localizer["vacancies"]</a></li>
            </ul>

            @RenderSection("Search", required: false)
            @RenderSection("ColumsHandler", required: false)

        </aside>
        

    </section>


    <main>
        @RenderBody()
    </main>

    <footer class="container-fluid">
        <div class="row">
            <div class="col-sm-2 left-empty-part"></div>
            <div class="col-sm-8 container-fluid">
                <div class="row p-0-75 ">

                    <div class="col-sm-6">
                        <ul class="list-unstyled">
                            <li><!--TO DO: bank image container--><h5 class="text-white">@Localizer["aboutUs"]</h5></li>
                            <li>
                                <a href="https://github.com/Andrii4424" target="_blank">
                                    <img src="~/images/footer/github-logo.svg" alt="Github" class="footer-images" />
                                </a>

                            <li>
                            <li class="d-flex mt-2">
                                <a href="https://t.me/Pipsqueak3" class="text-reset text-decoration-reset" target="_blank">
                                    <img src="~/images/footer/telegram-logo.svg" alt="Telegram" class="footer-images" />
                                </a>
                                <a href="viber://chat?number=%2B380639615125" target="_blank">
                                    <img src="~/images/footer/viber-logo.svg" alt="Viber" class="footer-images ml-0-75" />
                                </a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-sm-6 text-white">
                        <ul class="list-unstyled">
                            <li><h6>@Localizer["contactUs"]</h6></li>
                            <li>Telegram: Pipsqueak3</li>
                            <li>andreyfalchevskiy@gmail.com</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-sm-2 rigth-empty-part"></div>
        </div>
    </footer>

    <div id="confirm-delete-window">
        <div id="delete-window">
            <h2>🗑️ @Localizer["confirmDelete"]</h2>
            <p id="confirm-delete-text"></p>
            <div class="delete-buttons">
                <button class="confirm-delete-button">@Localizer["delete"]</button>
                <button class="cancel-delete-button">@Localizer["cancel"]</button>
            </div>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
    <script type="module" src="~/js/_Layout.js" defer></script>
    @RenderSection("additionalScripts", required: false)
</body>
</html>